name: PR tests
on:
  pull_request:
    branches:
      - develop

jobs:
  start-test:
    # Add branch condition (Only for feature branches)
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [14, 16]
    
    # Run tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install setup
        run: npm install
      - name: Run tests
        run: npm run test

